# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IA6fqM94VKi6WIdu1T0ObZfEkJW7F2g
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import PowerTransformer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import precision_recall_curve


from google.colab import files
uploaded = files.upload()

df = pd.read_csv("student_dropout_dataset_v3.csv")

df.drop(["Student_ID"], axis= 1,inplace = True)
df.dropna(inplace = True)

X, y = df.drop(columns = ["Dropout"]),df["Dropout"]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

categorical_col = ["Gender","Internet_Access",
                   "Part_Time_Job","Scholarship","Semester",
                   "Department","Parental_Education" ]
numerical_col = ['Age',
       'Study_Hours_per_Day', 'Attendance_Rate',
       'Travel_Time_Minutes', 'Stress_Index',
       'GPA', 'Semester_GPA', 'CGPA']
skewed_col = ["Assignment_Delay_Days","Family_Income"]

skewed_pipe = Pipeline([
("power", PowerTransformer(method = "yeo-johnson"))])

cat_pipe = Pipeline([
("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

num_pipe = Pipeline([
("scaler", StandardScaler())])

preprocessor = ColumnTransformer([
("skew", skewed_pipe, skewed_col),
("cat", cat_pipe, categorical_col),
("num", num_pipe, numerical_col)])

base_model = LogisticRegression(
    solver="lbfgs",
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

pipe_base = Pipeline([
    ("preprocessing",preprocessor),
    ("base_model",base_model)
])

pipe_base.fit(X_train, y_train)

y_pred_base = pipe_base.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred_base)}")
print(f"Precision : {precision_score(y_test, y_pred_base)}")
print(f"Recall : {recall_score(y_test, y_pred_base)}")
print(f"F1 Score : {f1_score(y_test, y_pred_base)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_base)}")
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_base)
print(f"confusion matrix :\n{cm}")


# Probability for positive class ("Active")
y_proba = pipe_base.predict_proba(X_test)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)
plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
plt.plot([0, 1], [0, 1], linestyle="--")  # random line
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate (Recall)")
plt.title("ROC Curve")
plt.legend()
plt.show()


# Precision recall curve
precision, recall, thresholds = precision_recall_curve(
    y_test,
    y_proba,
)
plt.figure()
plt.plot(recall, precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.show()

# Confusion Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted label")
plt.ylabel("Actual label")
plt.title("Confusion Matrix")
plt.show()